version: '3'

tasks:
  run:
    desc: Run the Flow CLI via Go.
    cmds:
      - go run .

  publish:
    desc: Build and install the Flow CLI binary to ~/bin/f.
    cmds:
      - |
        set -euo pipefail
        bin_dir="$HOME/bin"
        target="$bin_dir/f"
        mkdir -p "$bin_dir"
        export GOCACHE="${GOCACHE:-$PWD/.gocache}"
        mkdir -p "$GOCACHE"
        go build -o "$target" .
        chmod 755 "$target"
        echo "Installed CLI to $target"
        fish_completion_dir="$HOME/.config/fish/completions"
        mkdir -p "$fish_completion_dir"
        cp completions/flow.fish "$fish_completion_dir/flow.fish"
        cp completions/f.fish "$fish_completion_dir/f.fish"
        echo "Installed fish completions to $fish_completion_dir/{flow.fish,f.fish}"
