complete -c flow -l help -s h -d 'Show help'
complete -c flow -l version -d 'Print version and exit'

complete -c flow -n '__fish_use_subcommand' -a help -d 'Help about any command'
complete -c flow -n '__fish_use_subcommand' -a updateGoVersion -d 'Upgrade Go using the workspace script'
complete -c flow -n '__fish_use_subcommand' -a deploy -d 'Deploy the current project using task publish'
complete -c flow -n '__fish_use_subcommand' -a commit -d 'Generate a commit message'
complete -c flow -n '__fish_use_subcommand' -a commitPush -d 'Generate a commit message and push'
complete -c flow -n '__fish_use_subcommand' -a commitReviewAndPush -d 'Review commit message interactively then push'
complete -c flow -n '__fish_use_subcommand' -a clone -d 'Clone a GitHub repository into ~/gh/<owner>/<repo>'
complete -c flow -n '__fish_use_subcommand' -a gitCheckout -d 'Check out a remote branch locally'
complete -c flow -n '__fish_use_subcommand' -a version -d 'Reports the current version of flow'

complete -c flow -n '__fish_seen_subcommand_from help' -a updateGoVersion -d 'Upgrade Go using the workspace script'
complete -c flow -n '__fish_seen_subcommand_from help' -a deploy -d 'Deploy the current project using task publish'
complete -c flow -n '__fish_seen_subcommand_from help' -a commit -d 'Generate a commit message'
complete -c flow -n '__fish_seen_subcommand_from help' -a commitPush -d 'Generate a commit message and push'
complete -c flow -n '__fish_seen_subcommand_from help' -a commitReviewAndPush -d 'Review commit message interactively then push'
complete -c flow -n '__fish_seen_subcommand_from help' -a clone -d 'Clone a GitHub repository into ~/gh/<owner>/<repo>'
complete -c flow -n '__fish_seen_subcommand_from help' -a gitCheckout -d 'Check out a remote branch locally'
complete -c flow -n '__fish_seen_subcommand_from help' -a version -d 'Reports the current version of flow'
